let data = [
    {
        'lang': "JavaScript",                                   // Data-Lang attribute
        'lang-name': "JavaScript",                              // Language name
        'lang-image': "./images/javascript.png",                // Language image
        'lang-image-attr': "JavaScript",                        // Language image alt
        'contributor': "Contributed by - kmrakash",             // Github Contributor (name)
        'contributor-link': "https://www.github.com/kmrakash",  // Github Contributor (link)
    },
    {
        'lang': "solidity",
        'lang-name': "Solidity",
        'lang-image': "./images/solidity.png",
        'lang-image-attr': "solidity",
        'contributor': "Contributed by - Azim Pathan",
        'contributor-link': "https://www.github.com/AzimPathan"
    },
    {
        'lang': "swift",
        'lang-name': "Swift",
        'lang-image': "./images/swift.png",
        'lang-image-attr': "swift",
        'contributor': "Contributed by - Azim Pathan",
        'contributor-link': "https://www.github.com/AzimPathan"
    },
    {
        'lang': "xml",
        'lang-name': "XML",
        'lang-image': "./images/xml.png",
        'lang-image-attr': "xml",
        'contributor': "Contributed by - Azim Pathan",
        'contributor-link': "https://www.github.com/AzimPathan"
    },
    {
        'lang': "scala",
        'lang-name': "Scala",
        'lang-image': "./images/scala.png",
        'lang-image-attr': "scala",
        'contributor': "Contributed by - Azim Pathan",
        'contributor-link': "https://www.github.com/AzimPathan"
    },
    
    {
        'lang': "Bash",
        'lang-name': "Bash",
        'lang-image': "./images/Bash.png",
        'lang-image-attr': "Bash",
        'contributor': "Contributed by - Sidharth Bankupalle",
        'contributor-link': "https://www.github.com/SidBthegr8",
    },
    {
        'lang': "C#",
        'lang-name': "C#",
        'lang-image': "./images/C-hash.png",
        'lang-image-attr': "C#",
        'contributor': "Contributed by - Sidharth Bankupalle",
        'contributor-link': "https://www.github.com/SidBthegr8",
    },
    {
        'lang': "Ruby",
        'lang-name': "Ruby",
        'lang-image': "./images/ruby.png",
        'lang-image-attr': "Ruby",
        'contributor': "Contributed by - Kushaan Gowda",
        'contributor-link': "https://www.github.com/kushaangowda",
    },
    {
        'lang': "Clojure",
        'lang-name': "Clojure",
        'lang-image': "./images/clojure.png",
        'lang-image-attr': "Clojure",
        'contributor': "Contributed by - Vishakha Kumari",
        'contributor-link': "https://github.com/vishakha71", 
    },
    {
        'lang': "Dart",
        'lang-name': "Dart",
        'lang-image': "./images/dart.png",
        'lang-image-attr': "Dart",
        'contributor': "Contributed by - Ashutosh Krishna",
        'contributor-link': "https://www.github.com/ashutoshkrris",
    },
    {
        'lang': "Groovy",
        'lang-name': "Groovy",
        'lang-image': "./images/groovy.png",
        'lang-image-attr': "Groovy",
        'contributor': "Contributed by - Vishakha Kumari",
        'contributor-link': "https://github.com/vishakha71", 
    },
    {
        'lang': "BASIC",
        'lang-name': "BASIC",
        'lang-image': "./images/BASIC.png",
        'lang-image-attr': "BASIC",
        'contributor': "Contributed by - Sidharth Bankupalle",
        'contributor-link': "https://www.github.com/SidBthegr8",
    },
    {
        'lang': "Logo",
        'lang-name': "Logo",
        'lang-image': "./images/Logo.png",
        'lang-image-attr': "Logo",
        'contributor': "Contributed by - Sidharth Bankupalle",
        'contributor-link': "https://www.github.com/SidBthegr8",
    },
    {
        'lang': "PHP",
        'lang-name': "PHP",
        'lang-image': "./images/php.png",
        'lang-image-attr': "PHP",
        'contributor': "Contributed by - Aditee Singh",
        'contributor-link': "https://www.github.com/aditee-singh",
    },
    {
        'lang': "Python",
        'lang-name': "Python",
        'lang-image': "./images/python.png",
        'lang-image-attr': "Python",
        'contributor': "Contributed by - Ashutosh Krishna",
        'contributor-link': "https://www.github.com/ashutoshkrris",
    },
    {
        'lang': "Go",
        'lang-name': "Go",
        'lang-image': "./images/go.png",
        'lang-image-attr': "Go",
        'contributor': "Contributed by - hey-mikey",
        'contributor-link': "https://www.github.com/hey-mikey",
    },
    {
        'lang': "C++",
        'lang-name': "C++",
        'lang-image': "./images/cpp.png",
        'lang-image-attr': "C++",
        'contributor': "Contributed by - Sidharth Bankupalle",
        'contributor-link': "https://www.github.com/SidBthegr8",
    },
    {
        'lang': "C",
        'lang-name': "C",
        'lang-image': "./images/c.png",
        'lang-image-attr': "C",
        'contributor': "Contributed by - Kushaan Gowda",
        'contributor-link': "https://www.github.com/kushaangowda",
    },
    {
        'lang': "R",
        'lang-name': "R",
        'lang-image': "./images/R.png",
        'lang-image-attr': "R",
        'contributor': "Contributed by - Utpal Prajapati",
        'contributor-link': "https://www.github.com/Utpal29",
    },
    {
        'lang': "Java",
        'lang-name': "Java",
        'lang-image': "./images/java.png",
        'lang-image-attr': "Java",
        'contributor': "Contributed by - Jean Choi",
        'contributor-link': "https://www.github.com/choijean",
    },
    {
        'lang': "Kotlin",
        'lang-name': "Kotlin",
        'lang-image': "./images/kotlin.png",
        'lang-image-attr': "Kotlin",
        'contributor': "Contributed by - MasterBrian99",
        'contributor-link': "https://www.github.com/MasterBrian99",
    },
    {
        'lang': "JavaScript DOM",
        'lang-name': "JavaScript DOM",
        'lang-image': "./images/javascript_dom.png",
        'lang-image-attr': "JavaScript DOM",
        'contributor': "Contributed by - Chawklate",
        'contributor-link': "https://www.github.com/Chawklate",
    },
    {
        'lang': "MATLAB",
        'lang-name': "MATLAB",
        'lang-image': "./images/MATLAB.png",
        'lang-image-attr': "MATLAB",
        'contributor': "Contributed by - Manisha Kumari",
        'contributor-link': "https://www.github.com/krimanisha",
    },
    {
        'lang': "Perl",
        'lang-name': "Perl",
        'lang-image': "./images/perl.png",
        'lang-image-attr': "Perl",
        'contributor': "Contributed by - Alberto Jauregui",
        'contributor-link': "https://www.github.com/albertojauregui",
    },
    {
        'lang': "XQuery",
        'lang-name': "XQuery",
        'lang-image': "./images/XQuery.png",
        'lang-image-attr': "XQuery",
        'contributor': "Contributed by - Aaditya Raj",
        'contributor-link': "https://www.github.com/Aaditya-Raj7",
    },
    {
        'lang': "Batch File",
        'lang-name': "Batch File",
        'lang-image': "./images/Batch.png",
        'lang-image-attr': "Batch File",
        'contributor': "Contributed by - Monica Munoz",
        'contributor-link': "https://www.github.com/sarcastic22101",
    },
    {
        'lang': "Typescript",
        'lang-name': "Typescript",
        'lang-image': "./images/typescript.png",
        'lang-image-attr': "typescript",
        'contributor': "Contributed by - asthakri50",
        'contributor-link': "https://www.github.com/asthakri50",
    },
    {
        'lang': "css",
        'lang-name': "css",
        'lang-image': "./images/css.png",
        'lang-image-attr': "css",
        'contributor': "Contributed by - asthakri50",
        'contributor-link': "https://www.github.com/asthakri50",
    },
    {
        'lang': "haskell",
        'lang-name': "haskell",
        'lang-image': "./images/haskell.png",
        'lang-image-attr': "haskell",
        'contributor': "Contributed by - Supriya Kumari",
        'contributor-link': "https://www.github.com/12345supu",
    },
    {
        'lang': "objective C",
        'lang-name': "objective C",
        'lang-image': "./images/objective C.png",
        'lang-image-attr': "objective C",
        'contributor': "Contributed by - Supriya Kumari",
        'contributor-link': "https://www.github.com/12345supu",
    },
    {
        'lang': "vb",
        'lang-name': "vb",
        'lang-image': "./images/vb.png",
        'lang-image-attr': "vb",
        'contributor': "Contributed by - Supriya Kumari",
        'contributor-link': "https://www.github.com/12345supu",
    },
    {
        'lang': "Red",
        'lang-name': "Red",
        'lang-image': "./images/Red.png",
        'lang-image-attr': "Red",
        'contributor': "Contributed by - Aditya Raj",
        'contributor-link': "https://www.github.com/Aaditya-Raj7",
    },
    {
        'lang': "cpp",
        'lang-name': "cpp",
        'lang-image': "./images/cpp.png",
        'lang-image-attr': "cpp",
        'contributor': "Contributed by - Sidharth Bankupalle",
        'contributor-link': "https://www.github.com/SidBthegr8",
    },
    {
        'lang': "rust",
        'lang-name': "rust",
        'lang-image': "./images/rust.png",
        'lang-image-attr': "rust",
        'contributor': "Contributed by - Manisha Kumari",
        'contributor-link': "https://www.github.com/krimanisha",
    },
    {
        'lang': "Eta",
        'lang-name': "Eta",
        'lang-image': "./images/Eta.png",
        'lang-image-attr': "Eta",
        'contributor': "Contributed by - Radha Kumari",
        'contributor-link': "https://www.github.com/12345radha",
    },
]
